-- GROUP BY --


-- 69¸¸
SELECT 
    REGIONID
    , AVG(QTY) 
    FROM KOPO_CHANNEL_RESULT_NEW 
    GROUP BY REGIONID
    ORDER BY REGIONID;


-- 12¸¸
SELECT * FROM KOPO_CHANNEL_SEASONALITY_NEW;

SELECT 
    REGIONID
    , PRODUCT
    , AVG(QTY) 
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    WHERE 1=1 
    GROUP BY REGIONID, PRODUCT
    ORDER BY REGIONID, PRODUCT;
    
SELECT 
    YEARWEEK
    , AVG(QTY) 
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    WHERE 1=1 
    GROUP BY YEARWEEK
    ORDER BY YEARWEEK;
    
SELECT 
    PRODUCT
    , AVG(QTY) 
    FROM KOPO_CHANNEL_SEASONALITY_NEW
    WHERE 1=1 
    GROUP BY PRODUCT
    ORDER BY PRODUCT;