
-- 테이블스페이스 조회--
SELECT * FROM DBA_TABLESPACES;

-- 파일 조회 --
SELECT * FROM DBA_DATA_FILES;

-- 테이블스페이스 생성 --
CREATE TABLESPACE TS_CHAE02
	datafile 'E:\oracle1\DATA\TS_CHAE02.dbf' SIZE 1024M
	AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
	SEGMENT SPACE MANAGEMENT AUTO;

-- 사용자생성 --
CREATE USER SECHAE1
		IDENTIFIED BY SECHAE1
		DEFAULT TABLESPACE TS_CHAE02
		TEMPORARY TABLESPACE TEMP;
		
-- 사용자 권한주기 --
GRANT CONNECT, RESOURCE, DBA TO SECHAE1;

-- 사용자 조회 --
SELECT * FROM DBA_USERS;